// Original relative path: constants.js

export const TEXTS = {
  title: "Portfolio Simulation — Chart + Speed",
  header: "Portfolio Value simulation with operator {operatorName}",
  controls_hour: "Step",
  controls_play: "▶︎ Play",
  controls_pause: "❚❚ Pause",
  controls_speed: "Speed",
  controls_speed_unit: "(ms between steps)",
  file_loader_label: "Load Data File (.json)",
  file_status_loading: "Loading data...",
  file_status_default: "Default data loaded.",
  file_status_loaded: "File loaded:",
  metrics_datetime: "Hour",
  metrics_available_money: "Available Money",
  metrics_cashout: "Cashout",
  metrics_position_values: "Position values",
  metrics_pnl_cumulated: "P&L cumulated",
  open_positions_caption: "OPEN POSITION",
  open_positions_none: "No open positions at this step.",
  open_positions_symbol: "Symbol",
  open_positions_quantity: "Quantity",
  open_positions_purchase_price: "Purchase Price",
  open_positions_current_price: "Current Price",
  open_positions_value: "Value",
  closed_positions_caption: "CLOSED POSITION",
  closed_positions_none: "No closed positions at this step.",
  closed_positions_symbol: "Symbol",
  closed_positions_quantity: "Quantity",
  closed_positions_purchase_price: "Purchase Price",
  closed_positions_current_price: "Current Price",
  closed_positions_value: "Value",
  closed_positions_pnl: "PnL",
  closed_positions_pnl_pct: "PnL %",
  tip: "Tip: use the <b>Step</b> slider to navigate manually. The <b>Speed</b> adjusts the interval (ms) between two frames when playback is active.",
  locale: "en-US",
};